# Generated by Django 6.0.4 on 2026-06-10 00:23

import store.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product.product_image_path),
        ),
    ]
